from pathlib import Path
from typing import Optional

ARDUINO_SKETCH_TEMPLATE = '''// Auto-generated by Osmograph Firmware Compiler
// Board: {board}
// Sensors: {sensors}
// Pins: {pins}

#define SENSOR_COUNT {sensor_count}
const int sensorPins[SENSOR_COUNT] = {{ {pin_list} }};
const char* sensorNames[SENSOR_COUNT] = {{ {name_list} }};

unsigned long lastPrint = 0;
int printInterval = {interval_ms};

void setup() {{
    Serial.begin(115200);
    analogReadResolution(12);
    for (int i = 0; i < SENSOR_COUNT; i++) {{
        pinMode(sensorPins[i], INPUT);
    }}
}}

void loop() {{
    unsigned long now = millis();
    if (now - lastPrint >= printInterval) {{
        lastPrint = now;
        Serial.print("OSM");
        for (int i = 0; i < SENSOR_COUNT; i++) {{
            int val = analogRead(sensorPins[i]);
            Serial.print(",");
            Serial.print(val);
        }}
        Serial.println();
    }}
}}
'''

PLATFORMIO_TEMPLATE = '''[env:{board}]
platform = {platform}
board = {board}
framework = arduino
monitor_speed = 115200
'''


class FirmwareCompiler:

    @staticmethod
    def generate_sketch(
        sensors: list[str],
        pins: list[int],
        board: str = "esp32",
        interval_ms: int = 100,
    ) -> str:
        pin_list = ", ".join(str(p) for p in pins)
        name_list = ", ".join(f'"{s}"' for s in sensors)

        return ARDUINO_SKETCH_TEMPLATE.format(
            board=board,
            sensors=", ".join(sensors),
            pins=", ".join(str(p) for p in pins),
            sensor_count=len(sensors),
            pin_list=pin_list,
            name_list=name_list,
            interval_ms=interval_ms,
        )

    @staticmethod
    def generate_platformio_ini(
        board: str = "esp32",
    ) -> str:
        platform_map = {
            "esp32": "espressif32",
            "arduino_uno": "atmelavr",
            "raspberry_pi_pico": "raspberrypi",
        }
        platform = platform_map.get(board, "espressif32")
        return PLATFORMIO_TEMPLATE.format(board=board, platform=platform)

    @staticmethod
    def export_sketch(
        output_dir: str | Path,
        sensors: list[str],
        pins: list[int],
        board: str = "esp32",
        interval_ms: int = 100,
    ) -> Path:
        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)

        src_dir = out / "src"
        src_dir.mkdir(parents=True, exist_ok=True)

        sketch = FirmwareCompiler.generate_sketch(sensors, pins, board, interval_ms)
        sketch_path = src_dir / "main.cpp"
        sketch_path.write_text(sketch)

        platformio = FirmwareCompiler.generate_platformio_ini(board)
        ini_path = out / "platformio.ini"
        ini_path.write_text(platformio)

        return out
